name: image_classifier_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - tensorflow>=2.4.0
    - numpy>=1.19.2
    - matplotlib>=3.3.2
    - pillow>=8.0.0
    - scikit-learn>=0.23.2
    - tensorflow-datasets>=4.4.0
    - jupyterlab